// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgmdI2FPPVhd_r0l3Lj_166Y0JnCzrbcw',
    appId: '1:503776607332:web:956e619b4be64308b73371',
    messagingSenderId: '503776607332',
    projectId: 'docdoc-app-ad256',
    authDomain: 'docdoc-app-ad256.firebaseapp.com',
    storageBucket: 'docdoc-app-ad256.firebasestorage.app',
    measurementId: 'G-TMSWG3SYJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADe63ocV3IHv-j3A4yifnYa2eyQUdP_2w',
    appId: '1:503776607332:android:15d11da2a17b5c35b73371',
    messagingSenderId: '503776607332',
    projectId: 'docdoc-app-ad256',
    storageBucket: 'docdoc-app-ad256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9jwkK9RHNpYeT3qOaZUxyPwd-topNiQA',
    appId: '1:503776607332:ios:3df9d39c2944998cb73371',
    messagingSenderId: '503776607332',
    projectId: 'docdoc-app-ad256',
    storageBucket: 'docdoc-app-ad256.firebasestorage.app',
    iosBundleId: 'com.example.flutterAdvanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9jwkK9RHNpYeT3qOaZUxyPwd-topNiQA',
    appId: '1:503776607332:ios:3df9d39c2944998cb73371',
    messagingSenderId: '503776607332',
    projectId: 'docdoc-app-ad256',
    storageBucket: 'docdoc-app-ad256.firebasestorage.app',
    iosBundleId: 'com.example.flutterAdvanced',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgmdI2FPPVhd_r0l3Lj_166Y0JnCzrbcw',
    appId: '1:503776607332:web:2cb9cbcaf763f6deb73371',
    messagingSenderId: '503776607332',
    projectId: 'docdoc-app-ad256',
    authDomain: 'docdoc-app-ad256.firebaseapp.com',
    storageBucket: 'docdoc-app-ad256.firebasestorage.app',
    measurementId: 'G-0YBKZLQNDZ',
  );
}
